//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input/AltarGameInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @AltarGameInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @AltarGameInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""AltarGameInput"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""f97ac094-3e9f-434f-9597-65ad1b4dd75a"",
            ""actions"": [
                {
                    ""name"": ""Agree"",
                    ""type"": ""Button"",
                    ""id"": ""073ba7a2-fc99-467a-b264-ae36125603c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Disagree"",
                    ""type"": ""Button"",
                    ""id"": ""7769128c-3787-4b1e-9d3f-8926d453d91e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ee2cd84b-9cd5-46e5-af99-fc7b6a9c7f71"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Agree"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""14ace043-3d45-4ae7-a4c3-41f0f2fee90d"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Disagree"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Agree = m_Player.FindAction("Agree", throwIfNotFound: true);
        m_Player_Disagree = m_Player.FindAction("Disagree", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Agree;
    private readonly InputAction m_Player_Disagree;
    public struct PlayerActions
    {
        private @AltarGameInput m_Wrapper;
        public PlayerActions(@AltarGameInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Agree => m_Wrapper.m_Player_Agree;
        public InputAction @Disagree => m_Wrapper.m_Player_Disagree;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Agree.started += instance.OnAgree;
            @Agree.performed += instance.OnAgree;
            @Agree.canceled += instance.OnAgree;
            @Disagree.started += instance.OnDisagree;
            @Disagree.performed += instance.OnDisagree;
            @Disagree.canceled += instance.OnDisagree;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Agree.started -= instance.OnAgree;
            @Agree.performed -= instance.OnAgree;
            @Agree.canceled -= instance.OnAgree;
            @Disagree.started -= instance.OnDisagree;
            @Disagree.performed -= instance.OnDisagree;
            @Disagree.canceled -= instance.OnDisagree;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnAgree(InputAction.CallbackContext context);
        void OnDisagree(InputAction.CallbackContext context);
    }
}
