name: dotnet format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-code-formatting:
    runs-on: self-hosted
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Creating project
        run: dotnet new classlib --name Fantasy-Quest --output ./Fantasy-Quest

      - name: Deleting garbage
        run: rm ./Fantasy-Quest/Class1.cs

      - name: Add .editorconfig
        run: wget https://raw.githubusercontent.com/Kiuh/KiuhTools/main/VSEditorConfig/vs.editorconfig -o Fantasy-Quest/.editorconfig

      - name: Show content
        run: ls -a -l Fantasy-Quest

      - name: Run dotnet format
        run: dotnet format Fantasy-Quest/Fantasy-Quest.csproj --verbosity diagnostic --verify-no-changes --no-restore --exclude Fantasy-Quest/
      
      - name: Run csharpier format
        run: dotnet-csharpier ./Fantasy-Quest/Assets/Scripts --check

      
  
