name: dotnet format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-format-dotnet:
    runs-on: self-hosted
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Creating project
        run: dotnet new classlib --name Fantasy-Quest --output ./Fantasy-Quest

      - name: Deleting garbage
        run: rm ./Fantasy-Quest/Class1.cs
      
      - name: Create file
        run: |
          touch Fantasy-Quest/AddContentToProject.ps
          printf "param([String]\$path, [String]\$include)\n" >> Fantasy-Quest/AddContentToProject.ps1
          printf "\$proj = [xml](Get-Content \$path)\n" >> Fantasy-Quest/AddContentToProject.ps1
          printf "[System.Console]::WriteLine(\"\")\n" >> Fantasy-Quest/AddContentToProject.ps1
          printf "[System.Console]::WriteLine(\"AddItemToProject {0} on {1}\", \$include,\$path)\n" >> Fantasy-Quest/AddContentToProject.ps1
          printf "\$xmlns = \"http://schemas.microsoft.com/developer/msbuild/2003\"\n" >> Fantasy-Quest/AddContentToProject.ps1
          printf "\$itemGroup = \$proj.CreateElement(\"ItemGroup\", \$xmlns);\n" >> Fantasy-Quest/AddContentToProject.ps1
          printf "\$proj.Project.AppendChild($itemGroup);\n" >> Fantasy-Quest/AddContentToProject.ps1
          printf "\$contentNode = \$proj.CreateElement(\"Content\", \$xmlns);\n" >> Fantasy-Quest/AddContentToProject.ps1
          printf "\$contentNode.SetAttribute(\"Include\", \$include);\n" >> Fantasy-Quest/AddContentToProject.ps1
          printf "\$itemGroup.AppendChild(\$contentNode)\n" >> Fantasy-Quest/AddContentToProject.ps1
          printf "\$proj.Save(\$path)\n" >> Fantasy-Quest/AddContentToProject.ps1

      - name: Give execution permission
        run: chmod +x ./Fantasy-Quest/AddContentToProject.ps1
      - name: Execute file
        run: pwsh ./Fantasy-Quest/AddContentToProject.ps1 "Fantasy-Quest.csproj" ".editorconfig"

      - name: Run dotnet format
        run: dotnet format Fantasy-Quest/Fantasy-Quest.csproj --verbosity diagnostic --verify-no-changes --no-restore --exclude Fantasy-Quest --include Fantasy-Quest/Assets/Scripts

  check-format-cscharpier:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run csharpier format
        run: dotnet csharpier '.\Fantasy-Quest\Assets\Scripts\' --check
  
