name: dotnet format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-code-formatting:
    runs-on: self-hosted
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Creating project
        run: dotnet new classlib --name Fantasy-Quest --output ./Fantasy-Quest

      - name: Deleting garbage
        run: rm ./Fantasy-Quest/Class1.cs

      - name: Add .editorconfig
        run: wget -O Fantasy-Quest/.editorconfig https://raw.githubusercontent.com/Mara-Games-Studios/Fantasy-Quest/main/Fantasy-Quest/.editorconfig

      - name: Check content
        run: |
          ls -a -l Fantasy-Quest
          cat Fantasy-Quest/.editorconfig

      - name: Run dotnet format
        run: dotnet format Fantasy-Quest/Fantasy-Quest.csproj --verify-no-changes --include Fantasy-Quest/Assets/Scripts -v d
      
      - name: Run csharpier format
        run: dotnet-csharpier 'Fantasy-Quest\Assets\Scripts\' --check

      
  
