name: dotnet format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-format-dotnet:
    runs-on: self-hosted
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Creating project
        run: dotnet new classlib --name Fantasy-Quest --output ./Fantasy-Quest

      - name: Deleting garbage
        run: rm ./Fantasy-Quest/Class1.cs

      - name: Add .editorconfig
        run: |
         curl -O ./Fantasy-Quest/.editorconfig https://github.com/Kiuh/KiuhTools/blob/main/VSEditorConfig/.editorconfig
         ll ./Fantasy-Quest

      - name: Run dotnet format
        run: dotnet format Fantasy-Quest/Fantasy-Quest.csproj --verbosity diagnostic --verify-no-changes --no-restore --exclude Fantasy-Quest --include Fantasy-Quest/Assets/Scripts

  check-format-cscharpier:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run csharpier format
        run: dotnet csharpier '.\Fantasy-Quest\Assets\Scripts\' --check
  
