name: dotnet format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-format-dotnet:
    runs-on: self-hosted
    
    steps:
      #- name: Setup .NET
      #  uses: actions/setup-dotnet@v3
      #  with:
      #    dotnet-version: '8.0.x'
      #    cache: true

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run dotnet format
        run: dotnet format Fantasy-Quest/Fantasy-Quest.sln --verbosity diagnostic --verify-no-changes --no-restore

  check-format-cscharpier:
    runs-on: self-hosted

    steps:
      #- name: Setup .NET
      #  uses: actions/setup-dotnet@v3
      #  with:
      #    dotnet-version: '8.0.x'
      #    cache: true

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run csharpier format
        run: dotnet csharpier '.\Fantasy-Quest\Assets\Scripts\' --check
  
